<installer> modified

diff --git a/etc/install b/etc/install
--- a/etc/install
+++ b/etc/install
@@ -234,24 +234,22 @@ deploy_dotfiles() {
 
 # Initialize
 initialize_dotfiles() {
-  if [ "$1" = 'init' ]; then
-    e_newline
-    e_header 'Initializing dotfiles...'
+  e_newline
+  e_header 'Initializing dotfiles...'
 
-    if is_debug; then
-      :
+  if is_debug; then
+    :
+  else
+    if [ -f Makefile ]; then
+      make init
     else
-      if [ -f Makefile ]; then
-        make init
-      else
-        log_fail 'Makefile: Not found'
-        exit 1
-      fi
+      log_fail 'Makefile: Not found'
+      exit 1
     fi
-
-    e_newline
-    e_done 'Initialize'
   fi
+
+  e_newline
+  e_done 'Initialize'
 }
 
 # Install
